// Auth
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

// Errors
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';


// Posts
export const POST_LOADING = 'POST_LOADING'
export const POST_LOADED = 'POST_LOADED'
export const POST_UNLOADED = 'POST_UNLOADED'

// Comments
export const COMMENT_LOADING = 'COMMENT_LOADING'
export const COMMENT_LOADED = 'COMMENT_LOADED'

export const DESTROY_SESSION = 'DESTROY_SESSION'

// EMAILS
export const EMAILS_LOADING = 'EMAILS_LOADING'
export const EMAILS_LOADED = 'EMAILS_LOADED'
export const EMAILS_UNLOADED = 'EMAILS_UNLOADED'
export const SENDING_EMAIL = 'SENDING_EMAIL'
export const EMAIL_SENT = 'EMAIL_SENT'
export const COLLECT_EMAILS = 'COLLECT_EMAILS'
